config/routes.rb
Emarket::Application.routes.draw do

  get "welcome/index"

  get "welcome/about"

  get "welcome/faq"

  get "welcome/contact"

  resources :posts

  devise_for :users

  root :to => 'welcome#index'

end

app/models/post.rb
class Post < ActiveRecord::Base


  attr_accessible :contact, :description, :name, :price, :itemtype, :image, :status


  has_attached_file :image, :styles => {
  										:thumb => "300x300#"
  }


  validates_attachment_content_type :image, :content_type => ["image/jpg", "image/jpeg", "image/png", "image/gif"]

  validates :name, :contact, :price, :itemtype, :status, :presence => true

  belongs_to :user, inverse_of: :posts

def self.search(search)
  if search
    where('name LIKE ? OR description LIKE ? OR itemtype LIKE ? OR status LIKE ? OR contact LIKE ?', "%#{search}%", "%#{search}%", "%#{search}%", "%#{search}%", "%#{search}%")
  else
    scoped
  end
end




end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many  :posts, inverse_of: :user, dependent: :destroy

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body

  validates :email,format:{
  	with: %r{\@(trincoll.edu)\Z}i,
  	message: 'Must be a @trincoll.edu email'
  }



end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  # GET /posts
  # GET /posts.json

  before_filter :authenticate_user!

  helper_method :sort_column, :sort_direction

  def index
    #@posts = Post.all 
    #@posts = Post.order(sort_column + " " + sort_direction)
    @posts = Post.search(params[:search]).order(sort_column + " " + sort_direction).paginate(:page => params[:page], :per_page => 10)

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @posts }
    end
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
    @post = Post.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @post }
    end
  end

  # GET /posts/new
  # GET /posts/new.json
  def new
    @post = Post.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @post }
    end
  end

  # GET /posts/1/edit
  def edit
    @post = Post.find(params[:id])
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(params[:post])
    @post.user = current_user

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render json: @post, status: :created, location: @post }
      else
        format.html { render action: "new" }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /posts/1
  # PUT /posts/1.json
  def update
    @post = Post.find(params[:id])

    respond_to do |format|
      if @post.update_attributes(params[:post])
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post = Post.find(params[:id])
    @post.destroy

    respond_to do |format|
      format.html { redirect_to posts_url }
      format.json { head :no_content }
    end
  end

  def sort_column
    Post.column_names.include?(params[:sort]) ? params[:sort] : "name"
  end
  
  def sort_direction
    %w[asc desc].include?(params[:direction]) ? params[:direction] : "asc"
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end

  def about
  end

  def faq
  end

  def contact
  end
end
 

app/helpers/application_helper.rb
module ApplicationHelper
	def sortable(column, title = nil)
	  title ||= column.titleize
	  css_class = column == sort_column ? "current #{sort_direction}" : nil
	  direction = column == sort_column && sort_direction == "asc" ? "desc" : "asc"
	  link_to title, {:sort => column, :direction => direction}, {:class => css_class}
	end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Bantam E-Market</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <!--<p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>-->
</head>
<body>

<div class="container">
  <ul class="nav nav-tabs">
    <li> <%= link_to "Home", root_path, class: 'btn btn-lg btn-info' %> </li>
    <li> <%= link_to "All Posts", posts_path, class: 'btn btn-lg' %> </li>
    <li> <%= link_to "About Us", welcome_about_path, class: 'btn btn-lg' %> </li>
    <li> <%= link_to "Contact", welcome_contact_path, class: 'btn btn-lg' %> </li>
    <li> <%= link_to "FAQs", welcome_faq_path, class: 'btn btn-lg' %> </li>
    <% if user_signed_in? %>
      <li> <%= link_to('Logout', destroy_user_session_path, :method => :delete, class: 'btn btn-lg btn-warning', data: { confirm: 'Are you sure you want to log out?'} ) %></li>
    <% end %>
  </ul>

<% if notice %>
    <p class="alert alert-success"><%= notice %></p>
<% end %>

<% if alert %>
    <p class="alert alert-danger"><%= alert %></p>
<% end %>

<%= yield %>

</div>

</body>
</html>

app/views/posts/_form.html.erb
<%= form_for(@post, :html => { :multipart => true}) do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<div class="field">
    <%= f.label :status %>
    <%= f.select(:status, options_for_select([['For Sale', 'For Sale'], ['To Buy', 'To Buy']]), {include_blank: true})  %><br />
    
  </div>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %><br />
  </div>

  <div class="field">
    <%= f.label :description %>
    <%= f.text_area :description %><br />
  </div>

  <div class="field">
    <%= f.label :itemtype %>
    <%= f.select(:itemtype, options_for_select([['Book', 'Book'], ['Electronics', 'Electronics'], ['Furniture', 'Furniture'], ['Other', 'Other']]), { include_blank: true})  %><br />
  </div>

  <div class="field">
    <%= f.label :price %>
    <%= f.text_field :price %><br />
  </div>
  <div class="field">
    <%= f.label :contact %>
    <%= f.text_field :contact %><br />
  </div>

<div class="field">
  <%= f.label :image %>
  <%= f.file_field :image %><br />
</div>
<br />

<div class="actions">
    <%= f.submit class: 'btn btn-lg btn-success' %>
</div>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form' %>

<%= link_to 'Show', @post, class: 'btn btn-mini' %> |
<%= link_to 'Back', posts_path, class: 'btn btn-mini btn-warning' %>

app/views/posts/index.html.erb
<h1 align="center">All Posts</h1>


<%= form_tag posts_path, :method => 'get', :id => "posts_search" do %>
  <p>
    <%= text_field_tag :search, params[:search] %>
    <%= submit_tag "Search", :name => nil %>
  </p>
  
<% end %>



<body class="container">

<div class="media">
    <div class="media-body">
        <table class="table table-hovered">
            <thead>
              <tr>
                <th><%= sortable "status" %></th>
                <th><%= sortable "name" %></th>
                <th>Description</th>
                <th><%= sortable "itemtype", "Item Type" %></th>
                <th><%= sortable "price", "Price ($)" %></th>
                <th>Contact</th>
                <th></th>
                <th></th>
                <th></th>
              </tr>
            </thead>

            <tbody>
                <% @posts.each do |post| %>
                  <tr>
                    <td><%= post.status %></td>
                    <td><%= post.name %></td>
                    <td><%= post.description %></td>
                    <td><%= post.itemtype %></td>
                    <td><%= number_to_currency(post.price) %></td>
                    <td><%= post.contact %></td>
                    <td><%= link_to 'Show', post, class: 'btn btn-mini btn-success' %></td>
                    <% if current_user == post.user %>
                        <td><%= link_to 'Edit', edit_post_path(post), class: 'btn btn-mini btn-warning' %></td>
                        <td><%= link_to 'Destroy', post, method: :delete, class: 'btn btn-mini btn-danger', data: { confirm: 'Are you sure?' } %></td>
                    <% end %>
                  </tr>
                <% end %>
            </tbody>
        </table>
    </div>
</div>
<br />

<%= will_paginate @posts %>

<%= link_to 'New Post', new_post_path, class: 'btn btn-lg btn-info' %>

app/views/posts/new.html.erb
<h1>New post</h1>

<%= render 'form' %>

<%= link_to 'Back', posts_path, class: 'btn btn-mini btn-warning' %>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Status:</b>
  <%= @post.status %>
</p>

<p>
  <b>Name:</b>
  <%= @post.name %>
</p>

<p>
  <b>Description:</b>
  <%= @post.description %>
</p>

<p>
  <b>Type:</b>
  <%= @post.itemtype %>
</p>

<p>
  <b>Price:</b>
  <%= number_to_currency(@post.price) %>
</p>


<p>
  <b>Contact:</b>
  <%= @post.contact %>
</p>

<% if @post.image? %>
  <%= image_tag @post.image.url(:thumb) %>
  <br />
  <!--<%= link_to @post.image.url, @post.image.url %>-->
<%end%>

<% if current_user == @post.user %>
<%= link_to 'Edit', edit_post_path(@post), class: 'btn btn-mini btn-info' %> |
<% end %>
<%= link_to 'Back', posts_path, class: 'btn btn-mini btn-warning' %>

app/views/welcome/about.html.erb
<h1 align="center">About Us</h1>
<p> Year after year, students at Trinity College struggle to find affordable prices for textbooks, dorm supplies, electronics and other college necessities. Students tend to spend an excess amount of money buying textbooks and other supplies, and when they sell them back, they receive a minimal fraction of what they paid. A solution to this problem is the Bantam E-Market that acts as a forum for students to buy and sell these college necessities. Students can post textbooks or other supplies to sell at a self defined price, and at the same time can browse for the textbooks or supplies they want to buy. Bantam E-Market provides the contact information of the buyer and seller. The website itself will not handle any payment information, like credit or debit cards, however it will require campus specific login credentials. This website simplifies the process of buying and selling college goods by keeping everything on campus, which eliminates shipping time and costs. It also allows for students to earn more money selling back their materials, but at the same time, allows for students to save money when buying materials. </p>

app/views/welcome/contact.html.erb
<h1 align="center">Contact Info</h1>
<p align="center">300 Summit St. Hartford, CT 06106 USA</p>
<b></b>
<p align="center">Email: bantan.emarket@gmail.com</p>

app/views/welcome/faq.html.erb
<h1 align="center">FAQ's</h1>
<div class="media">
	<div class="media body">
		<ul>
			<li>
				<p class="lead">What is the Bantam E-market?</p>
				<p>The Bantam E-Market is an online platform where Trinity students can post any item they want to sell so that others in the the community can purchase them. Alternatively, one could post an item they want to buy, so that other users who own such item can sell it.</p>
			</li>
			<p></p>
			
			<li>
				<p class="lead">How does the Bantam E-market work?</p>
				<p>Go to "All Posts" and create a new post. Then wait until someone contacts you and determine the final terms of the transaction with them.</p>
			</li>

			<li>
				<p class="lead">Does the Bantam E-market manage payments?</p>
				<p>No, we do not manage the monetary transactions between users. You must get in contact with the buyer or seller and aggree on a date to meet and determine the final price of the transaction.</p>
			</li>

			<li>
				<p class="lead">Why use the Bantam E-Market instead of Ebay, Amazon or any other online market?</p>
				<p>The Bantam E-Market is only used by the Trinity Community. This has many advantages:
					<ul>
						<li> No shipping costs</li>
						<li> Buying items from the Trinity Community ensures that you can see what you are buying <em>before</em> buying it.</li>
						<li> Books owned by Trinity students are probably the exact edition and come from the same publisher as the one you will need.</li>
						<li> You can trust other members of the Trinity Community as opposed to having to trust someone you have never seen and will never meet in your life</li>
					</ul>
				</p>
			</li>

			<li> 
				<p class="lead">Need more answers?</p>
				<p> Read our <%= link_to "About Us", welcome_about_path %> page or send us an email, we will answer any further questions you have.</p>
			</li>
		</ul>

		
	<div>
<div>

app/views/welcome/index.html.erb
<h1 align="center">Bantam E-Market</h1>


<% if user_signed_in? %>
	<p align="center">Welcome, <%= current_user.email %> </p>

<% else %>
<h2>Sign In</h2>
		<p>Please Login or Sign Up to Continue</p>
		<%= form_for("user", :url => user_session_path) do |f| %>
		<p> Email</p>
		<p><%= f.text_field :email %></p>
		<p> Password </p>
		<p><%= f.password_field :password %></p>
	  	<p><%= f.check_box :remember_me %>
	  	<%= f.label :remember_me %></p>
	  	<p><%= f.submit 'Sign in' %></p>
	  	<p><%= link_to "Forgot your password?", new_password_path('user') %></p>
	  	<p><%= link_to "Sign Up", new_user_registration_path %></p>
		<% end %>
<% end %>